package com.example.request_bot.session;

public enum UserState {
    IDLE,
    WAITING_FOR_NAME,
    WAITING_FOR_DEPARTMENT,
    WAITING_FOR_POSITION,
    WAITING_FOR_REQUEST_TYPE,
    WAITING_FOR_REQUEST_DESCRIPTION,
    WAITING_FOR_REQUEST_PRIORITY,
    WAITING_FOR_REQUEST_CONFIRM,
    WAITING_FOR_MANAGER_COMMENT,
    WAITING_FOR_MANAGER_SEARCH
}
